# Generated by Django 5.1.3 on 2024-12-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='每小时停车费')),
                ('total_spots', models.PositiveIntegerField(default=100, verbose_name='总车位数')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('small', '小型车'), ('large', '大型车')], default='small', max_length=20)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in', '在场'), ('out', '已离开')], default='in', max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='缴费金额')),
            ],
        ),
    ]
