# Generated by Django 5.1.3 on 2024-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='每小时停车费')),
                ('total_spots', models.PositiveIntegerField(default=100, verbose_name='总车位数')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='缴费金额'),
        ),
    ]
